AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/AbcSize:
  Max: 18

Style/Documentation:
  Enabled: false
