default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  user: postgres
  password: postgres

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production